services:
  - type: web
    name: fasthtml-app
    runtime: python
    buildCommand: pip install python-fasthtml
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7